name: Michael Bradvica

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  WEBAPP_PATH: ./src/MB.MVC
  AZURE_WEBAPP_NAME: michaelbradvica
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish '${{ env.WEBAPP_PATH }}' -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app'

      - name: Deploy To Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app
